### ISSUE TITLE
Chapter 5: Functional Programming (Code Review)

### ISSUE THREAD

**Issue by zuff-digital** [sanklamm/brave-clojure-2022#2]
## General Comments

I appreciate how thoroughly you test your solutions, I should follow suit. 

## Exercise 2

I like that you practiced using multi-arity here, I'm still not used to thinking in those terms. Should I think of it as a useful tool to reach for when recursing? 

I took two different approaches to solving this one, both strike me as pretty different from your take, and I realize now that neither quite behaves the same way as `comp` in the case of receiving a scalar value instead of a fn, good catch.

## Exercise 3

Well done, I inverted the `if/else` branches but other than that reached the same solution.

## Exercise 5

Ahhh, I didn't account for the arguments to the function in my solution, I assumed either a single function or a fully contained anonymous function, an unfair assumption given how the docs say `update-in` should work.

**Comment by sanklamm** [comment]
Thanks a lot for the review.
